### ISSUE TITLE
Hovering in js editor leads to errors in the log

### ISSUE THREAD

**Issue by akurtakov** [mickaelistria/eclipse-bluesky#10]
!ENTRY org.eclipse.lsp4e 4 0 2017-04-20 10:43:21.414
!MESSAGE 
!STACK 0
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.eclipse.lsp4e.operations.hover.LSBasedHover.getHoverInfo(LSBasedHover.java:91)
	at org.eclipse.ui.internal.genericeditor.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:48)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:166)

**Comment by mickaelistria** [comment]
With the latest update, seems like LSP4E doesn't receive any response from the JSTS server...

**Comment by mickaelistria** [comment]
Do you see anything working for JSTS in general with latest version?

**Comment by akurtakov** [comment]
I don't see any hover or autocomplete or similar if this is what you ask for. FWIW, js editing in html files works fine.

**Comment by akurtakov** [comment]
It was staled node modules in my build.
