### ISSUE TITLE
Eclipse dies with heapdump

### ISSUE THREAD

**Issue by vogella** [mickaelistria/eclipse-bluesky#12]
See screenshot.

![bluesky](https://cloud.githubusercontent.com/assets/139910/26077345/03ebe0ba-39bc-11e7-9e76-a52943e04222.png)

**Comment by mickaelistria** [comment]
I can reproduce it when I open a MANIFEST.MF file.
Stacktrace is
```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
	at java.lang.StringBuffer.append(StringBuffer.java:367)
	at java.io.BufferedReader.readLine(BufferedReader.java:370)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.eclipse.pde.internal.core.content.BundleManifestDescriber.describe(BundleManifestDescriber.java:51)
	at org.eclipse.core.internal.content.ContentTypeCatalog.describe(ContentTypeCatalog.java:226)
	at org.eclipse.core.internal.content.ContentTypeCatalog.collectMatchingByContents(ContentTypeCatalog.java:197)
	at org.eclipse.core.internal.content.ContentTypeCatalog.internalFindContentTypesFor(ContentTypeCatalog.java:409)
	at org.eclipse.core.internal.content.ContentTypeCatalog.internalFindContentTypesFor(ContentTypeCatalog.java:458)
	at org.eclipse.core.internal.content.ContentTypeCatalog.findContentTypesFor(ContentTypeCatalog.java:306)
	at org.eclipse.core.internal.content.ContentTypeMatcher.findContentTypesFor(ContentTypeMatcher.java:51)
	at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$1.run(ConnectDocumentToLanguageServerSetupParticipant.java:80)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```
As this is the only file I see failing that way, I imagine this can be in issue in the particular BundleManifestDescriber, or a missing `.close()` somewhere in LSP4E code (which doesn't show up with other files...)

**Comment by mickaelistria** [comment]
upstream issue ( https://bugs.eclipse.org/bugs/show_bug.cgi?id=516896 ) was fixed and bluesky was re-built and re-deploy to make the patch available.
