### ISSUE TITLE
javascript Code completion doesn't seem to work

### ISSUE THREAD

**Issue by ericahrens** [mickaelistria/eclipse-bluesky#13]
````
 var xxg = 455;
 
(function test() {
	var myarray = [];

	function csome() {
	}

	for(var i=0;i<10;i++) {
		// cursor is here !!
	}
	
})();
````

CTRL+Space does not render any proposals.

**Comment by bleidiessel** [comment]
I double checked it on Windows 10 and have the same behavior.

**Comment by vogella** [comment]
Looks like the language servers are not available by default. @mickaelistria is this an error or should this be available by default.

**Comment by mickaelistria** [comment]
Can you please share whether the <ws>/.metadata/.log file shows interesting related info?

**Comment by mickaelistria** [comment]
The language server are enabled by default. BlueSky works well for several users. I suspect what can make the difference are things such as the version of `node` that's available in PATH and so on. I'll need the log and more details about the environment and node version to understand the root cause.

**Comment by ericahrens** [comment]
node version is 6.9.1

**Comment by ericahrens** [comment]
Here is something that pops up:

eclipse.buildId=4.7.0.I20170517-2000
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/eclipse/eclipse_oxygen/ws/

This is a continuation of log file C:\eclipse\eclipse_oxygen\ws\.metadata\.bak_0.log
Created Time: 2017-05-19 13:50:56.344

org.eclipse.text
Error
Fri May 19 13:53:54 CEST 2017
Problems occurred when invoking code from plug-in: "org.eclipse.text".

java.lang.RuntimeException: java.io.IOException: Die Pipe wird gerade geschlossen
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:68)
	at org.eclipse.lsp4e.ProjectSpecificLanguageServerWrapper.lambda$4(ProjectSpecificLanguageServerWrapper.java:228)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:95)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.sendCancelNotification(RemoteEndpoint.java:129)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint$1.cancel(RemoteEndpoint.java:108)
	at org.eclipse.lsp4e.outline.LSSymbolsContentProvider.refreshTreeContentFromLS(LSSymbolsContentProvider.java:103)
	at org.eclipse.lsp4e.outline.LSSymbolsContentProvider.documentChanged(LSSymbolsContentProvider.java:98)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged2(AbstractDocument.java:744)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:713)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:697)
	at org.eclipse.jface.text.AbstractDocument.fireDocumentChanged(AbstractDocument.java:771)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1102)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.replace(SynchronizableDocument.java:173)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1120)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.replace(SynchronizableDocument.java:161)
	at org.eclipse.jface.text.DefaultDocumentAdapter.replaceTextRange(DefaultDocumentAdapter.java:233)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7355)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8203)
	at org.eclipse.swt.custom.StyledText.doBackspace(StyledText.java:2335)
	at org.eclipse.swt.custom.StyledText.invokeAction(StyledText.java:7144)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6007)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6034)
	at org.eclipse.swt.custom.StyledText.lambda$1(StyledText.java:5732)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1130)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1126)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1547)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4962)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:364)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4843)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2560)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3815)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: java.io.IOException: Die Pipe wird gerade geschlossen
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:65)
	... 59 more

**Comment by mickaelistria** [comment]
Ok, I'm using node 7.10. Maybe Language Server require a more recent
version. Can you please try?
If this is the cause, then a patch checking node version and warning if too
old would be welcome ;)

**Comment by angelozerr** [comment]
If problem comes from node.js version, I think https://github.com/mickaelistria/eclipse-bluesky/issues/23 should fix this problem.

**Comment by mickaelistria** [comment]
Can you please try again? We recently changes the language server for JavaScript and the new one may work better.
