### ISSUE TITLE
NPE after installing bluesky

### ISSUE THREAD

**Issue by vogella** [mickaelistria/eclipse-bluesky#16]
All servers (CSS, HTML, JSTLLanguageServer) give me NPE errror after installation into an Eclipse 4.7 SDK.
Exception:
```
java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.eclipse.bluesky.InitializeLaunchConfigurations.getNodeJsLocation(InitializeLaunchConfigurations.java:78)
	at org.eclipse.bluesky.CSSLanguageServer.<init>(CSSLanguageServer.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.lsp4e.LSPStreamConnectionProviderRegistry$1.run(LSPStreamConnectionProviderRegistry.java:114)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.lsp4e.LSPStreamConnectionProviderRegistry.initialize(LSPStreamConnectionProviderRegistry.java:110)
	at org.eclipse.lsp4e.LSPStreamConnectionProviderRegistry.<init>(LSPStreamConnectionProviderRegistry.java:88)
	at org.eclipse.lsp4e.LSPStreamConnectionProviderRegistry.getInstance(LSPStreamConnectionProviderRegistry.java:77)
	at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$1.run(ConnectDocumentToLanguageServerSetupParticipant.java:93)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by vogella** [comment]
@mickaelistria my second try with Bluesky. Still fails after installation for me.

**Comment by mickaelistria** [comment]
Can you check whether #17 improve stuff a bit?

**Comment by vogella** [comment]
Local build fails for me see #18

**Comment by vogella** [comment]
Looks good with the pull request, I'm now getting a dialog that I'm missing nodejs and not a null pointer exception anymore.

**Comment by mickaelistria** [comment]
Thanks for checking and reporting!
