### ISSUE TITLE
Autocompletion doesn't work after a file is close

### ISSUE THREAD

**Issue by jabby** [mickaelistria/eclipse-bluesky#45]
Today I made some new test to integrate the support of less and css support. I notice a problem with completion. Maybe the bug is not in bluesky but in lsp4e instead.

How to reproduce : 
- Open a css file with one rule
- use the completion in the rule
- close the file
- open it again 
- try again the completion : the completion fail

The following log is present in console : 
````
!ENTRY org.eclipse.lsp4e 4 0 2017-09-08 12:51:08.672
!MESSAGE java.io.IOException: Stream closed
!STACK 0
java.lang.RuntimeException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:68)
	at org.eclipse.lsp4e.ProjectSpecificLanguageServerWrapper.lambda$4(ProjectSpecificLanguageServerWrapper.java:175)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:122)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:77)
	at com.sun.proxy.$Proxy24.completion(Unknown Source)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.lambda$1(LSContentAssistProcessor.java:112)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.computeCompletionProposals(LSContentAssistProcessor.java:117)
	at org.eclipse.ui.internal.genericeditor.ContentAssistProcessorRegistry$ContentAssistProcessorExtension.computeCompletionProposals(ContentAssistProcessorRegistry.java:107)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$4(AsyncCompletionProposalPopup.java:242)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:65)
	... 22 more
````

**Comment by mickaelistria** [comment]
Seems like a bug in LSP4E.

**Comment by jabby** [comment]
I just create a bug report here : https://bugs.eclipse.org/bugs/show_bug.cgi?id=522579

**Comment by mickaelistria** [comment]
Upstream is fixed. So marking this one as closed too.
