### ISSUE TITLE
Eclipse BlueSky doesn't work with Photon M6

### ISSUE THREAD

**Issue by angelozerr** [mickaelistria/eclipse-bluesky#63]
I have downloaded Eclipse Photon M6 and installed bluesky with Marketplace and hover, completion doesn't work with HTML Language server:

```
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.eclipse.lsp4e.ProjectSpecificLanguageServerWrapper.getServerCapabilities(ProjectSpecificLanguageServerWrapper.java:408)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getMatchingStartedWrapper(LanguageServiceAccessor.java:283)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrapper(LanguageServiceAccessor.java:219)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfoFor(LanguageServiceAccessor.java:182)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfoFor(LanguageServiceAccessor.java:168)
	at org.eclipse.lsp4e.operations.hover.LSBasedHover.initiateHoverRequest(LSBasedHover.java:185)
	at org.eclipse.lsp4e.operations.hover.LSBasedHover.getHoverRegion(LSBasedHover.java:163)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverRegion(CompositeTextHover.java:98)
	at org.eclipse.jface.text.TextViewerHoverManager.computeInformation(TextViewerHoverManager.java:139)
	at org.eclipse.jface.text.AbstractInformationControlManager.doShowInformation(AbstractInformationControlManager.java:1142)
	at org.eclipse.jface.text.AbstractHoverInformationControlManager$MouseTracker.mouseHover(AbstractHoverInformationControlManager.java:518)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:209)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4433)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1086)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4243)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3822)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:681)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:595)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
```

The strange thing is that highlight is working. There is the same problem with other language server.

**Comment by mickaelistria** [comment]
Highlight as a failback so it can work without LS. I'll investigate.

**Comment by mickaelistria** [comment]
@angelozerr this is working for me. Can you please check which version of LSP4E is installed on your IDE where you see the issue?

**Comment by angelozerr** [comment]
I have downloaded a fresh version of Photon and install http://repository.jboss.org/nexus/content/unzip/unzip/org/eclipse/bluesky/repository/0.1.0-SNAPSHOT/repository-0.1.0-SNAPSHOT.zip-unzip/

**Comment by mickaelistria** [comment]
I just updated TP and node_modules. Can you please try again?
