### ISSUE TITLE
Error while computing document highlights

### ISSUE THREAD

**Issue by LucasBullen** [mickaelistria/eclipse-bluesky#68]
Pulled from master
`mvn clean verify` succeeded
No error when imported `org.eclipse.bluesky` in my workspace which also includes lsp4e
Open an empty .css file
Receive the following message from the server:
```
[Error]	Error while computing document highlights for file:///home/lbullen/eclipseWorkspaces/runtime-EclipseApplication(1)/test/test.css: Cannot read property 'version' of undefined
TypeError: Cannot read property 'version' of undefined
    at Object.get (/home/lbullen/git/eclipse-bluesky/org.eclipse.bluesky/target/vscode/VSCode-linux-x64/resources/app/extensions/css/server/out/languageModelCache.js:27:35)
    at /home/lbullen/git/eclipse-bluesky/org.eclipse.bluesky/target/vscode/VSCode-linux-x64/resources/app/extensions/css/server/out/cssServerMain.js:181:38
    at Object.runSafe (/home/lbullen/git/eclipse-bluesky/org.eclipse.bluesky/target/vscode/VSCode-linux-x64/resources/app/extensions/css/server/out/utils/errors.js:23:17)
    at /home/lbullen/git/eclipse-bluesky/org.eclipse.bluesky/target/vscode/VSCode-linux-x64/resources/app/extensions/css/server/out/cssServerMain.js:179:21
    at handleRequest (/home/lbullen/git/eclipse-bluesky/org.eclipse.bluesky/target/vscode/VSCode-linux-x64/resources/app/extensions/css/server/node_modules/vscode-jsonrpc/lib/main.js:361:27)
    at processMessageQueue (/home/lbullen/git/eclipse-bluesky/org.eclipse.bluesky/target/vscode/VSCode-linux-x64/resources/app/extensions/css/server/node_modules/vscode-jsonrpc/lib/main.js:252:17)
    at Immediate.<anonymous> (/home/lbullen/git/eclipse-bluesky/org.eclipse.bluesky/target/vscode/VSCode-linux-x64/resources/app/extensions/css/server/node_modules/vscode-jsonrpc/lib/main.js:242:13)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```
Receiving no successful messages and as the above is sent over lsp4e causes errors in lsp4j when trying to parse.

**Comment by jabby** [comment]
Hello @LucasBullen I can't reproduced your problem with the last version of the project. Do you still have this issue?
If you can reproduce, please share the operating mode to reproduce the problem.

Thanks.

**Comment by LucasBullen** [comment]
Working with master and this is no longer an issue
