### ISSUE TITLE
Error in outline view when bluesky run as child eclipse.

### ISSUE THREAD

**Issue by akurtakov** [mickaelistria/eclipse-bluesky#9]
Output in outline view is 
ENOENT: no such file or directory 'open /path/to/eclipse/file:/path/to/project/file:/path/to/file.js'

**Comment by akurtakov** [comment]
!MESSAGE ENOENT: no such file or directory, open '/home/akurtakov/opt/oxygen/eclipse/file:/home/akurtakov/work/runtime-launchConfiguration/test/file:/home/akurtakov/work/runtime-launchConfiguration/test/test.js'
!STACK 0
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: ENOENT: no such file or directory, open '/home/akurtakov/opt/oxygen/eclipse/file:/home/akurtakov/work/runtime-launchConfiguration/test/file:/home/akurtakov/work/runtime-launchConfiguration/test/test.js'
	at org.eclipse.lsp4e.ProjectSpecificLanguageServerWrapper.logMessage(ProjectSpecificLanguageServerWrapper.java:266)
	at org.eclipse.lsp4e.ProjectSpecificLanguageServerWrapper.lambda$4(ProjectSpecificLanguageServerWrapper.java:209)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mickaelistria** [comment]
Seems like the p2 repo doesn't contain the last version of LSP4E.

**Comment by mickaelistria** [comment]
@akurtakov This should now be a bit better. Can you please try reloading the TP and/or updating your version of bluesky to make sure you have a recent org.eclispe.lsp4e bundle (>= 0.2.0.20170413...)

**Comment by akurtakov** [comment]
Refreshed (I have  0.2.0.201704132140 now) and what I see in outline view is "Computing symbols..." for both js and ts files. I assume this is not the correct behavior also.

**Comment by jabby** [comment]
I tried to launch an Eclipse child. The completion (ctrl+space) does not work for files.  
The completion and the application freezed.

**Comment by mickaelistria** [comment]
@jabby can you please create a separate issue for that. Those symptoms seem to have a different cause than the ones mentioned initially there.

**Comment by akurtakov** [comment]
This was stale node modules in my build.
